// import type { Metadata } from "next";
import localFont from 'next/font/local';
import './globals.scss';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

const gtAmericaMono = localFont({
  src: [
    {
      path: './fonts/GTAmericaMono-Light.woff2',
      weight: '300',
    },
    {
      path: './fonts/GTAmericaMono-Regular.woff2',
      weight: '400',
    },
    {
      path: './fonts/GTAmericaMono-Medium.woff2',
      weight: '500',
    },
    {
      path: './fonts/GTAmericaMono-Bold.woff2',
      weight: '700',
    },
  ],
  variable: '--font-gtAmericaMono',
});
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${gtAmericaMono.variable} `}>
        <main>
          <Header />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
